---
hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Clone wars
description: Maak een spel waarin je de aarde tegen ruimtemonsters moet beschermen
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - title: Inleiding
  - title: Wat heb je nodig
  - title: Maak een ruimteschip
  - title: Bliksemschichten
  - title: Vliegende ruimte-nijlpaarden
  - title: Exploderend ruimteschip
  - title: Verdwijnende nijlpaarden
  - title: Fruit vleermuis
  - title: Game over
  - title: 'Uitdaging: verbeter je spel'
