hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: क्लोन वार्स
description: एक गेम बनाएं जिसमें आपको पृथ्वी को अन्तरिक्ष के दैत्यों से बचाना होगा
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: 'games'
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: भूमिका
- title: आपको किसकी ज़रूरत होगी
- title: स्पेसशिप बनाना
- title: लाइटनिंग बोल्ट
- title: फ्लाइंग स्पेस-हिप्पोस
- title: एक्सप्लोडिंग स्पेसशिप
- title: गायब हो रहे हिप्पोस
- title: फ्रूट बैट
- title: गेम ओवर
- title: 'चुनौती: अपनी गेम में सुधार करें'
