hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: 克隆战争
description: 创作一个游戏，在游戏中，你必须战胜太空怪物，拯救地球
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: '游戏'
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: 介绍
- title: 你将需要什么
- title: 制作一艘宇宙飞船
- title: 闪电球
- title: 会飞的太空河马
- title: 爆炸的宇宙飞船
- title: 消失的河马
- title: 果蝠
- title: 游戏结束
- title: '挑战：完善你的游戏'
