hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Guerras de Clones
description: Crea un juego en que cual tengas que salvar la Tierra de monstruos espaciales
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Introducción
- title: Construir la nave espacial
- title: Rayos
- title: Hipopótamos espaciales voladores
- title: ¡Murciélagos de la fruta!
- title: Fin del Juego
- title: 'Reto: Mejorar el juego'