hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Brwydro Clonau
description: Dysga sut i greu gêm lle mae angen achub y Ddaear rhag anghenfilod y gofod
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps: 
- title: Cyflwyniad
- title: Creu Llong Ofod
- title: Mellt
- title: Hipopotamws yn hedfan yn y gofod
- title: Ystlumod Ffrwythau!
- title: Gêm drosodd
- title: 'Her: Gwella dy gêm'