---
hero_image: images/clone-wars.png
theme: violet
duration: 2
listed: false
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Ratovi klonova
description: Napravi igru u kojoj treba da spasiš Zemlju od svemirskih čudovišta
original_url: https://codeclubprojects.org/en-GB/scratch/clone-wars
interests: games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - title: Uvod
  - title: Šta će ti biti potrebno
  - title: Izrada svemirskog broda
  - title: Munje
  - title: Leteći svemirski nilski konji
  - title: Eksplozija svemirskog broda
  - title: Nilski konji koji nestaju
  - title: Slijepi miš sa voćem
  - title: Kraj igre
  - title: 'Izazov: poboljšaj svoju igru'
